from setuptools import setup, find_packages

setup(
    name="loopai",
    version="0.0.1",
    packages=find_packages(),
    package_data={
        "loopai": [
            "agents/Obtainer/datamixer/assets/**/*",
            "skills/Judger/docker/math_eval/*",
        ],
    },
    include_package_data=False,
    install_requires=[
        "langgraph>=0.6.7",
        "langgraph-checkpoint-sqlite>=3.0.0",
        "colorlog>=6.10.0",
        "rich>=13.0.0",
        "langchain>=0.3.27",
        "langchain-community>=0.3.0",
        "langchain-openai>=0.1.0",
        "langchain-core>=0.3.0",
        "langchain-text-splitters>=0.2.0",
        "omegaconf>=2.3.0",
        "PyYAML>=6.0",
        "httpx>=0.24.0",
        "chromadb>=0.4.0",
        "ddgs",
        # Download dependencies
        "huggingface_hub>=0.20.0",
        "datasets>=2.14.0",
        "kaggle>=1.5.0",
        "kagglehub>=0.2.0",
        "playwright>=1.40.0",
        "tenacity>=8.2.0",
        "requests>=2.31.0",
        "transformers>=4.30.0",
        # Keep these aligned with open-dataflow==1.0.10.
        "numpy<2.0.0",
        "pyarrow==20.0.0",
        # DataFlow API serving and Google/Vertex response proxy backends.
        "google-api-python-client",
        "google-cloud-aiplatform",
        "google-cloud-bigquery",
        "google-genai",
        # Reasoning math, benchmark evaluation, and Text2SQL operators.
        "word2number==1.1",
        "math-verify>=0.9.0",
        "json5>=0.15.0",
        "pymysql>=1.2.0",
        "sqlglot>=30.0.0",
        "mcp[cli]>=0.1.0",
        "tomlkit>=0.13.2",
        "aiosqlite>=0.21.0",
        "fastapi",
        "uvicorn",
        "pydantic",
        "tortoise-orm",
        "func-timeout",
        "psutil",
        "pyflakes>=3.4.0",
        "tree_sitter>=0.25.2",
        "tree-sitter-python>=0.25.0",
        "tree-sitter-javascript>=0.25.0",
        "tree-sitter-java>=0.23.5",
        "tree-sitter-cpp>=0.23.4",
        "tree-sitter-c>=0.24.1",
        "tree-sitter-c-sharp>=0.23.1",
        "tree-sitter-go>=0.25.0",
        "tree-sitter-rust>=0.24.0",
        "tree-sitter-ruby>=0.23.1",
        "tree-sitter-swift>=0.0.1",
        "tree-sitter-kotlin>=1.1.0",
        "tree-sitter-scala>=0.24.0",
        "tree-sitter-bash>=0.25.1",
        "tree-sitter-html>=0.23.2",
        "tree-sitter-css>=0.25.0",
        "tree-sitter-json>=0.24.8",
        "tree-sitter-yaml>=0.7.2",
        "tree-sitter-markdown>=0.5.1",
        "one-eval @ git+https://github.com/OpenDCAI/One-Eval.git@main",
        "open-dataflow==1.0.10",
        "vllm>=0.4.0",
    ],
    entry_points={
        "console_scripts": [
            "loopai-obtainercli=loopai.skills.ObtainerCLI.cli:main",
            "loopai-judger=loopai.skills.Judger.cli:main",
            "loopai-configer=loopai.skills.Configer.cli:main",
            "loopai-analyzer=loopai.skills.Analyzer.cli:main",
            "loopai-trainer=loopai.skills.Trainer.cli:main",
        ],
    },
    python_requires=">=3.12",
)
